### ISSUE TITLE
Update add and create command messages to match UG

### ISSUE THREAD

**Issue by Eola-Z** [AY2324S1-CS2103T-T08-2/tp#106]
Should only be done after we've finalized the two commands.

**Comment by Eola-Z** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/113225702/e5b2a712-a63c-4b0a-9327-f5f2412c0c8b)

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/b931bd30-85a0-44d0-92f1-b543a6463555)
