### ISSUE TITLE
Improve specificity of command error messages

### ISSUE THREAD

**Issue by Eola-Z** [AY2324S1-CS2103T-T08-2/tp#107]

**Comment by Eola-Z** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/113225702/79fc58cf-ca9d-4617-b8d6-65ca365df018)

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/2107b3b7-78d6-422c-b8ff-82525268c121)
