### ISSUE TITLE
Open other apps

### ISSUE THREAD

**Issue by nknguyenhc** [AY2324S1-CS2103T-T08-2/tp#108]
As a NetworkBook user, I wish to be able to open the relevant social media platform from the NetworkBook app so that I can quickly contact them on social media.

As a NetworkBook user, I wish to be able to open my email app from my NetworkBook app, so that I can quickly send an email when needed.

**Comment by Singa-pirate** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/58817781/4531ab38-6482-4a50-98dd-04b531df686d)
