### ISSUE TITLE
Check existing shortcuts and fix where applicable

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/tp#111]
As a user, I want to use commonly-available keyboard shortcuts, so that I can provide input more efficiently with shortcuts I am accustomed to.

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/2624679c-556b-4f7b-afda-e7bbcd0fe5c1)

**Comment by nknguyenhc** [comment]
Moved to v1.3b

**Comment by Singa-pirate** [comment]
Existing shortcuts:
- ctrl-C: copy text
- ctrl-V: paste text
- ctrl-X: cut text
- ctrl-Z: undo text
- ctrl-A: select all text
- ctrl/shift/fn + left/right: navigate in text
- Other windows shortcuts (windows-up/down: maximise/minimise window, alt-F4: close window)

All these shortcuts are working properly.
