### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by Singa-pirate** [AY2324S1-CS2103T-T08-2/tp#112]
When there's no input in the command line, using these shortcuts will auto-fill the command word:
- Add ctrl-N shortcut for `create` command
- Add ctrl-G shortcut for `edit` command
- Add ctrl-F shortcut for `find` command
- Add ctrl-U shortcut for `undo` command

Other shortcuts to add:
- Add ctrl-W shortcut to exit program
- Add ctrl-S shortcut that
  - prompts a success message to assure the user that the progress is auto-saved
  - deal with the case where permission of the data file is compromised 
- Add up/down arrow key shortcut to navigate previous commands

- Ensure shortcuts work across different OS

**Comment by Singa-pirate** [comment]
As a user, I want to use commonly-available keyboard shortcuts, so that I can provide input more efficiently with shortcuts I am accustomed to.

As a user, I want to use simple and easy-to-press shortcuts, so that I can remember and execute the shortcuts more easily.

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/56448966-985f-45fd-9e98-b45a6cb9825f)
