### ISSUE TITLE
Filter by course

### ISSUE THREAD

**Issue by Eola-Z** [AY2324S1-CS2103T-T08-2/tp#114]
As an NUS computing student, I wish to filter my list of contacts on NetworkBook by courses taken/taking, so that I can easily find and connect with individuals from a particular course.

**Comment by Eola-Z** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/113225702/6420e5db-6aad-4824-8412-17427abc4e96)

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/f1529d74-8350-48f8-9f22-37a4fb494b7b)
