### ISSUE TITLE
Filter by graduation year

### ISSUE THREAD

**Issue by Eola-Z** [AY2324S1-CS2103T-T08-2/tp#115]
As an NUS computing student, I wish to filter my list of contacts on NetworkBook by graduation year, so that I can easily find and connect with other NUS students/alumni from a particular year.

**Comment by Eola-Z** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/113225702/1c958021-2756-47bd-94a0-dbd7b7d284e3)

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/6676ba9a-c327-423a-b7c3-b4970bd8f25f)
