### ISSUE TITLE
Filter by specialisation

### ISSUE THREAD

**Issue by Eola-Z** [AY2324S1-CS2103T-T08-2/tp#116]
As an NUS computing student, I wish to filter my list of contacts on NetworkBook by specialisations, so that I can easily find and connect with individuals from a particular field of study.

**Comment by Eola-Z** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/113225702/3317d846-bc8d-4867-8c0d-6119e16d6c94)

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/53273f7e-4c6c-4961-ac3b-ca71ded09fcc)
