### ISSUE TITLE
Implement undo/redo function for networkbook data

### ISSUE THREAD

**Issue by awhb** [AY2324S1-CS2103T-T08-2/tp#117]
As an NUS computing student, I want to be able to undo and redo commands that alter the networkbook data state so that I can maintain data integrity and recover from accidental modifications to the networkbook data.

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/3221312d-9b12-4123-8516-257960e1b645)
