### ISSUE TITLE
Implement undo/redo function for networkbook display list

### ISSUE THREAD

**Issue by awhb** [AY2324S1-CS2103T-T08-2/tp#118]
As an NUS computing student, I want to be able to undo and redo commands that alter the networkbook display list so that I can toggle between display lists at different points of time.

**Comment by nknguyenhc** [comment]
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/285e1f89-ee05-42a6-b1d1-e34e3e3f9f5c)

**Comment by awhb** [comment]
Fixed #169
