### ISSUE TITLE
Undo occassionally does not work

### ISSUE THREAD

**Issue by nknguyenhc** [AY2324S1-CS2103T-T08-2/tp#184]
Steps to reproduce:
* Create a new contact list with at least 2 people, with each person having completely different courses 
(i.e. courses that do not have overlapping words).
* Close the app and open again.
* Click on a course button to filter by that course.
The app should show only that contact.
* Unfocus from the textbox and press Ctrl+Z.

Expected behaviour: The list should be reverted back to the original list with more than one person.

Actual behaviour: Nothing happens, the list still shows the same list of one person.

**Comment by Eola-Z** [comment]
Can confirm the same issue happens with sort and find command, I'm pretty sure it's because these commands are labelled as 'not changing data'
