### ISSUE TITLE
Create command creates new contact at the wrong index

### ISSUE THREAD

**Issue by xenosf** [AY2324S1-CS2103T-T08-2/tp#187]
<img width="918" alt="image" src="https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/40383042/a2e6f2cb-657e-4ecd-8716-eaade16fbb28">

Command result lists (last index + 1) but inserts new contact in a different position. It should insert at the end when the list is unsorted.

How to replicate:

* Execute create command

**Comment by awhb** [comment]
Remove index comment
