### ISSUE TITLE
[PE-D][Tester D] [Bug] Filter function with `taken` field not working as intended

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-2/tp#198]
`taken` parameter = `false`

![image.png](https://raw.githubusercontent.com/Zjinnnn/ped/main/files/c1292e36-0191-4c61-ae12-bd2a2de8a578.png)

`taken` parameter = `true`

![image.png](https://raw.githubusercontent.com/Zjinnnn/ped/main/files/6c7123b9-23a2-4a33-b5b0-e4a3d68e342d.png)

Platform: MacOS

Description:

As seen in the screenshots above, when running the `filter` command with `taken` field being set as `true`, results does not actually filter. `Charlotte Oliveiro` in the networkbook is supposed to have graduated as the `Graduation` is set to `AY1999/2000 Semester 2`. However, when `taken` is being passed, no noticeable difference is observed. 

Bug Replication:

Command: filter /by course /with computer /taken true

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Zjinnnn/ped#3

**Comment by nknguyenhc** [comment]
Duplicate with tester A issue 5.
