### ISSUE TITLE
[PE-D][Tester A] Adding information without name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-2/tp#202]
![image.png](https://raw.githubusercontent.com/Blizzeracz/ped/main/files/5209f1ad-09f6-4fcf-848d-aaff68312d9d.png)

The error message given does not correspond with the user input.

Perhaps there could be a different error message for this?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Blizzeracz/ped#1

**Comment by nknguyenhc** [comment]
Error message does correspond to the wrong user input.
AY2022 is not a valid AY.
This is the `add` command, not `create` command.
Rejected.
