### ISSUE TITLE
[PE-D][Tester E] 'list' command is not reflected in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-2/tp#204]
![Screenshot 2023-11-03 at 4.39.40 PM.png](https://raw.githubusercontent.com/freshcabbage123/ped/main/files/e36c5d4c-ee29-4080-898c-7b5decc7f086.png)
 
'list' command is in the app but is not shown in the UG. At least it is not found in the command summary or TOC.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: freshcabbage123/ped#6

**Comment by nknguyenhc** [comment]
Add 'list' command to the UG.
