### ISSUE TITLE
[PE-D][Tester C] Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-2/tp#209]
The shortcuts for the keyboard Auto-fill command preamble does not work on my computer. 
I am using a Macbook Pro with a M1 Chip.

Could possibly perform a smoke test with other OS to check if it works.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: DeltonCheng/ped#3

**Comment by nknguyenhc** [comment]
Bug is present.
