### ISSUE TITLE
[PE-D][Tester A] Parameter for email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-2/tp#212]
![image.png](https://raw.githubusercontent.com/Blizzeracz/ped/main/files/78c97096-b688-4a97-95f3-d0f6a349f602.png)

Should the domain for email contain a single . ? Just like the domain for links.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Blizzeracz/ped#4

**Comment by nknguyenhc** [comment]
Fixed.
