### ISSUE TITLE
[PE-D][Tester E] Discrepancy between phone number description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-2/tp#215]
![Screenshot 2023-11-03 at 5.04.21 PM.png](https://raw.githubusercontent.com/freshcabbage123/ped/main/files/c4185fc4-0211-4e6a-b4e3-a777fe541094.png)

in the UG, it is said that only numeric characters should be included but in the application, it is stated that the "+" can be included too.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: freshcabbage123/ped#9

**Comment by nknguyenhc** [comment]
Add to docs.
