### ISSUE TITLE
[PE-D][Tester C] Missing 'list' command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-2/tp#217]
UG is missing the list command, was unable to find out how I could list out all the contacts after using the filtering function.

My thought process was:
1) Filter the NetworkBook based on a certain filter
2) Return to start screen (list all contacts)

Could add the list command into UG so that it is clearer on how to head back to the 'main' page with all contacts

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DeltonCheng/ped#5

**Comment by nknguyenhc** [comment]
Add to docs.

**Comment by Eola-Z** [comment]
duplicate
