### ISSUE TITLE
[PE-D][Tester D] [Bug] Command follows format of error message but fails

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T08-2/tp#219]
![image.png](https://raw.githubusercontent.com/Zjinnnn/ped/main/files/f62fbb80-2d01-421b-aafc-48406b769c95.png)

Platform: MacOS

Description:

Error message when creating a new contact can be misleading. The error message states "Phone numbers should only contain numbers (and country code with "+" in front if applicable), and it should be at least 3 digits long". Technically, with the input `create /name tester /phone +123`, the phone number satisfies the condition of a 3 digits. However, the application rejects such command. 

The error message and User Guide did not state clearly the requirements for adding the country code with a "+". This is a minor issue that can be solved simply by clarifying it in the User Guide, as well as stating it in the error message more clearly.

Bug Replication:

Command: `create /name tester /phone +123`

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Zjinnnn/ped#6

**Comment by nknguyenhc** [comment]
Add `(excluding country code)` at the end of the error message.
