### ISSUE TITLE
[DG] Effort

### ISSUE THREAD

**Issue by nknguyenhc** [AY2324S1-CS2103T-T08-2/tp#292]
As per DG specs:

![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/87511888/7e4a94f9-d8d4-427b-b327-2194e075558b)

Should we do this? I feel this would be a repetition of the implementation section.

**Comment by awhb** [comment]
i don't think we need
our group has a lot of features that speak for themselves alr

**Comment by nknguyenhc** [comment]
Alright, I will close this issue soon if no one else has any comment.

**Comment by Singa-pirate** [comment]
I feel it's a nice-to-have section if we want to highlight our effort in testing, especially GUI tests which are not present in the AB3 project.

**Comment by nknguyenhc** [comment]
In that case in this appendix we say efforts for functional code are found in the above sections, and briefly mention what functional codes we have, and here we elaborate more on the testing efforts? For this part I think we only have GUI tests as a new testing method, so @Singa-pirate do u wanna take this task?

**Comment by Singa-pirate** [comment]
Yep okay

**Comment by nknguyenhc** [comment]
Actually @Singa-pirate I think testing should be a different section, possibly under `Implementation` section and before the `Documentation` section? For this appendix I feel it's more for efforts in general, and not about any particular section.

**Comment by Singa-pirate** [comment]
I think can still have this appendix section. I will briefly summarise the efforts on functional codes, then highlight all efforts possibly unseen by testers. Points I have in mind include:
1. Having a UniqueList implementation to hold all multi-valued fields
2. Refactoring prefix format
3. Implementation of `EditAction` and `DeleteFieldAction` to follow the "command" design pattern
4. Replacing all runtime errors with checked exceptions
5. Maintaining code coverage and adding GUI tests

**Comment by nknguyenhc** [comment]
Sounds great. For point 3, I feel like if u mention those 2, might as well mention the other commands, they r not simple in implementation. I feel that it can be left out, since we already have a big chunk of text on implementation of individual commands.

You may want to mention the class `JsonAdaptedProperty` as well.

**Comment by Singa-pirate** [comment]
Okay
