### ISSUE TITLE
[UG] Indicate what fields are allowed for each command

### ISSUE THREAD

**Issue by nknguyenhc** [AY2324S1-CS2103T-T08-2/tp#318]
This is especially for `create`, `add`, `edit` and `delete`.

**Comment by awhb** [comment]
Where to indicate?

**Comment by nknguyenhc** [comment]
Possibly have a bullet point under each command to list out the fields allowed in that command.

**Comment by Singa-pirate** [comment]
@nknguyenhc @awhb I think it will look neater if we put in the blue info boxes, as a paragraph above "To view a comprehensive list of fields..."

**Comment by awhb** [comment]
I see

**Comment by awhb** [comment]
Resolved by #314
